name: Build LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra

      - name: Build PDF
        run: pdflatex -interaction=nonstopmode -halt-on-error rian-rahman-resume.tex

      - name: Replace PDF
        run: |
          rm -f rian-rahman-resume.pdf
          mv rian-rahman-resume.pdf ./rian-rahman-resume.pdf

      - name: Configure Git
        run: |
          git config user.name "rian"
          git config user.email "rian.rahman@gatech.edu"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update PDF"
          git push
