name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended poppler-utils

      - name: Build PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error rian-rahman-resume.tex

      - name: Convert PDF to PNG
        run: |
          mkdir -p png
          pdftoppm -png rian-rahman-resume.pdf png

      - name: Configure Git
        run: |
          git config user.name "Rian Rahman"
          git config user.email "rian.rahman@gatech.edu"

      - name: Commit and Push Changes
        run: |
          git add rian-rahman-resume.pdf
          if [ -f "png/00001.png" ]; then
            git add png/00001.png
          fi
          git commit -m "Update rian-rahman-resume.pdf and PNG"
          git push
